### ISSUE TITLE
Discrepancy in Weights Output from main_finetune.py

### ISSUE THREAD

**Issue by qihan96** [Alpha-VLLM/LLaMA2-Accessory#30] opened 2023-08-15 23:36 UTC
Hi, the weights output from main_finetune.py does not align perfectly with the delta_weights provided in the Huggingface page. 

In the list of keys of the delta_weights of **llama_qformerv2_13B**, it includes all original llama keys and the following 6 additional keys for the image processing 

> [llma.start_img, llma.end_img, llma.qformer_proj.0.weight, llma.qformer_proj.0.bias, llma.qformer_proj.1.weight, llma.qformer_proj.1.bias].

However, in the list of keys read from running main_finetune.py's result **finetune/mm/alpacaLlava_llamaQformerv2Peft_13B/epoch0/consolidated.00-of-01.model.pth**, the list includes all lora weights and only the following 2 extra keys 

> [llma.qformer_proj.0.bias, llma.qformer_proj.1.bias].

Consequently, I can not merge the output weights with llama directly. I think the following functions are the reason why some projection layer tensors are not saved in the output. 

1.  The function defined in the transformer class excludes keys that do not have any of the string in the list ['norm', 'bias,' and 'lora']. https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/020e4c36c05d20ea38e13ed1c3f71cd7eabec448/accessory/model/LLM/llama_qformerv2_peft.py#L341
2. The function defined in the metaModel class calls 1. https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/020e4c36c05d20ea38e13ed1c3f71cd7eabec448/accessory/model/meta.py#L61
3. Function 2. is later used to set trainability. 
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/020e4c36c05d20ea38e13ed1c3f71cd7eabec448/accessory/model/meta.py#L66

    Why are projection layer's weights not part of the training? 
4. The saving function in misc.py therefore only saved two bias tensors for projection layers. https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/020e4c36c05d20ea38e13ed1c3f71cd7eabec448/accessory/util/misc.py#L350

Is main_finetuned.py not supposed to be used for finetuning Training of Multi-Model LLaMA 2? Do you have a script that combines the finetuned results with the llama 2 weights? Thanks for the help!

**Comment by ChrisLiu6** [comment] 2023-08-16 04:38
Hi! The root cause of your issue is that our fine-tuning pipeline consists of [two stages](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/finetune.md#two-stage-training-of-multi-model-llama-2), and `exps/finetune/mm/alpacaLlava_llamaQformerv2Peft_13B.sh` is for the second stage. Meanwhile, we've made some parameters (`[llma.start_img, llma.end_img, llma.qformer_proj.0.weight, llma.qformer_proj.1.weight]`) only trainable in the first stage (fine-tuning on large-scale image-text pairs).


Our stage-1 fine-tuning code will be released in one day or two, then you can follow our pipeline to run the complete two-stage finetune. Alternatively, if you want to simply skip stage 1, you may modify the `get_trainable_params` method 

https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/020e4c36c05d20ea38e13ed1c3f71cd7eabec448/accessory/model/LLM/llama_qformerv2_peft.py#L341

to 
``` python
    def get_trainable_params(self):
        trainable = {}
        for name, para in self.named_parameters():
            if not name.startswith("qformer."):
                trainable_key_words = ['norm', 'bias', 'lora', 'qformer_proj', '_img']
                if any([_ in name for _ in trainable_key_words]):
                    trainable[name] = para

        return trainable
```

By the way, we find that only saving trainable parameters brings much inconvenience in practical usage, so we have just made it optional:
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/f7c86298f12d3d0af5f8d9929332691119296303/accessory/util/misc.py#L356

**Comment by qihan96** [comment] 2023-08-16 16:29
The explanation makes a lot of sense. Thanks! What is the motivation for splitting into two stages?

**Closed** 2023-08-28 00:40 UTC
